### ISSUE TITLE
Profile consistency

### ISSUE THREAD

**Issue by rwky** [passport-next/passport#16]
It would appear that profiles aren't being generated cosistently across all modules.

e.g. Facebook does this:

```js
profile.name = {
    familyName: json.last_name,
    givenName: json.first_name,
    middleName: json.middle_name
};
```

Google does this:
```js
if (json.family_name || json.given_name) {
    profile.name = {
      familyName: json.family_name,
      givenName: json.given_name
    };
}
```

So Facebook will always have `profile.name.familyName` (though it maybe undefined) Google wil only have `profile.name.familyName` if a name value is returned from Google.

Personally I'd go for the Facebook method, that way people don't need to check if `profile.name` exists they just need to check `profile.name.whatever` 

I suggest that, all passport-next modules should return cosistent profile info where possible and leave values `undefined` where the login provider doesn't provide any information on that field.

Any comments (if not I'll assume everyone's ok with it and go ahead with impementation when I've time, I'll leave it a week or so before starting).

**Comment by adamreisnz** [comment]
I agree with having consistent profiles across the board (hence the few PR's recently, I noticed discrepancies between Google and Facebook).

Personally I'm not a fan of either method above, because it created empty undefined keys on the profile object, which can be annoying if you're iterating properties and you only expect to have existing data.

So if you don't want breaking changes, and always include a name object, I'd propose the following unified approach:

```js
profile.name = {};
if (json.last_name) {
  profile.name.familyName = json.last_name;
}
if (json.first_name) {
  profile.name.givenName = json.first_name;
}
if (json.middle_name) {
  profile.name.middleName = json.middle_name;
}
```

This will ensure only those name components will be set which actually exist, yet the name object itself will always be there.

I would prefer this approach across the board for other properties as well. For example birthday, gender are also set by default in the Facebook module and end up being undefined, which just adds noise imo (see https://github.com/passport-next/passport-facebook/pull/7).

**Comment by rwky** [comment]
Sounds like a reasonable compromise, as long as we don't end up causing any TypeErrors I'm happy.
